### ISSUE TITLE
DPU template with same name as parent displayed in pipelines editor

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Core#187]
I save as DPU template with same name as parent. After that I am unable to find in DPU Templates.
Probably there shouldn't be possibility to save DPU template with same name as parent.

**Comment by tomas-knap** [comment]
Regarding confusion on the canvas: In DPU detail dialog, there is always information about the parent DPU template. So it is always clear what is the parent of every DPU instance placed on the canvas. 

Note: Regarding expected behavior using same names of DPU templates and export/import feature, see:
https://github.com/UnifiedViews/Core/issues/356
