### ISSUE TITLE
Querying slow when large amount of graphs on input

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#188]
Querying slow when large amount of graphs is on input.
The actual data is not so large that the Metadata DPU queries would take so long. The only difference from other pipelines is that there is a large amount of graphs on the input (1 per XSLTed file), ~10K total.
![image](https://cloud.githubusercontent.com/assets/718827/4417321/34a1de50-4552-11e4-9511-0dc587370d80.png)

**Comment by tomas-knap** [comment]
Taken comment from #226: There is a workaround for specific cases ("per-graph" execution in t-sparqlConstruct & t-sparqlUpdate followed by a graph merger and then t-metadata) but generally the problem is that when there is a larger number of graphs (hundreds and more) the triplestore (both sesame and virtuoso) is unable to process a query with so many FROM clauses or graphs set in the Dataset.

**Comment by skrchnavy** [comment]
@tomas-knap - this is architectural question, how to handle this.

**Comment by skrchnavy** [comment]
@jakubklimek is this issue relevant in current version?

**Comment by tomas-knap** [comment]
As discussed with @jakubklimek, this is still relevant
