### ISSUE TITLE
Follow-up activities on feature/sso_fixes - final refactoring of #282

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#345]
Follow up of #282.

1 There should be only one method "hasPermission" on AuthAwarePermissionEvaluator class. But sometimes, a different method with the same and purpose is used, see: 
  * frontend/src/main/java/cz/cuni/mff/xrg/odcs/frontend/gui/dialog/PipelineExport.java
  * frontend/src/main/java/cz/cuni/mff/xrg/odcs/frontend/gui/components/SchedulePipeline.java
  * frontend/src/main/java/cz/cuni/mff/xrg/odcs/frontend/gui/views/Settings.java

Solution?: AuthAwarePermissionEvaluator class should be autowired to every class which requires "hasPermission" method, AuthAwarePermissionEvaluator.hasPermission should be used as the only method for checking permissions. 

2 DPUViewImpl.java - buttonCreateDPU.setVisible(utils.hasUserAuthority("dpuTemplate.create"));

This approach using utils.hasUserAuthority("dpuTemplate.create") is redundant to the standard approach: 

```
@Autowired
private AuthAwarePermissionEvaluator permissions;

permissions.hasPermission(pipeline, "pipeline.create");
```
which is used in most of the situations where permissions should be checked. 

Solution: Do not use Utils class to check permissions. Utils should not contain any auth/autorization methods. Use ALWAYS one class, the PermissionEvaluator class!

**Comment by eea03** [comment]
I wouldn't say that second approach is redundant to the first approach. Actually we are speaking about 2 different things:
1. First approach is used to check permissions on specific entity (pipeline, DPU, ...)
2. Second approach is used to check if user has some permission in general with no connection to a specific entity. 

Solution you suggest could work in a way that when hasPermission() method is given null as entity parameter, only permission is checked and entity is ignored. However I do not consider this as a clean solution because these two approaches really mean two different things which should be separated also in code.

In my current implementation I created a new bean (PermissionUtils) which contains methods for both checking permissions on entity and checking user permissions in general. This bean is always used now whenever permissions needed to be checked so there is no need to autowire 2 beans

**Comment by skrchnavy** [comment]
@tomas-knap what is proposed? Shall we implement these changes as you suggested or is there other decision / conclusion.

**Comment by tomas-knap** [comment]
@eea03 So one class (PermissionUtils) is used to check the permissions, so we can close this?

**Comment by eea03** [comment]
Yes, I did a refactoring and only this class is used to check the permissions.
I would close it

**Comment by skrchnavy** [comment]
Based on comments from @eea03, @tomas-knap please review and close.
