### ISSUE TITLE
When locale is missing in backend config, backend does not log.

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#346]
I upgraded UV from the latest develop. Backend stopped creating log files and stopped logging to databases. The error was an exception during backend start complaining about missing locale property  in config.properties. When I added locale = en_US, everything started working again.

**Comment by eea03** [comment]
Well, actually there are 2 reasons for this problem. First is that UV still does not have default values for mandatory parameters. This was discussed in #303 but as far as I know it has not been solved; 
The other reason is wrong exception handling in cz.cuni.mff.xrg.odcs.backend.AppEntry() run method; As Spring is initialized before initialization of locale, logs and DPUs, process runs even if exception is thrown; This is exactly this case, initialization of locale threw Exception so logging and DPUs initialization never even started. 
Correct behaviour should be to catch exception during initialization and shutdown application (destroy Spring context) if any exception occurrs. 
However, it is not so easy to implement becase context.close() does not behave as expected and task scheduler is not shut down immediatelly but continues to execute job which tries to connect to database which is not possible because EntityManager was already closed.
So further analysis is needed, prefferably from someone familiar with this code.

Conclusion is that backend proccess should end if any exception occurrs during initialization; 
Default mandatory configuration parameters are just other issue which should be solved too.

**Comment by skrchnavy** [comment]
@tomas-knap do you agree with the @eea03  conclusion:
_Not to start backend if any exception occurs during initialisation_ and to log properly why is not started? (stack trace is not enough, log must be clear and easy to understand where is the problem.

**Comment by tomas-knap** [comment]
OK, agree.

**Comment by tomas-knap** [comment]
As you wrote it important to give the user clear message where the problem was, not just stack trace.

**Comment by farky** [comment]
main issue was that application has not been correctly stopped because threads in scheduled task has not been set as daemon and in someones are used infinity loops. so jvm wait for them nevertheless app context has been closed (also with scheduler). 
User can get only message as obtained from underlying layer where exception has been caused with detailed stack trace of course. We cannot say no more. For instance in case which was written above user is notified that locale property is missing.
