### ISSUE TITLE
Scheduler table not refreshing after schedule detail window opened

### ISSUE THREAD

**Issue by eea03** [UnifiedViews/Core#546]
In scheduler view, there is a refresher that checks if any executions have changed and refreshes the table accordingly. This works until schedule detail window is opened (e.g. new schedule, edit schedule)
When schedule detail window is opened, refresher is removed - I suppose this is correct there is no need to refresh the table when modal window is opened.
However when detail window is closed, refresher is not restored and thus table will never be refreshed again (until browser refresh or UV menu click)

**Comment by eea03** [comment]
Fixed in https://github.com/UnifiedViews/Core/pull/547

**Comment by tomas-knap** [comment]
Fixed in commit https://github.com/UnifiedViews/Core/commit/76ec64493c2b9883c575d25c3a5603be879cc165, which is partly based on the adjustments proposed in https://github.com/UnifiedViews/Core/pull/547 (nevertheless, the whole https://github.com/UnifiedViews/Core/pull/547 is not yet accepted as this not only fixed this issue but also introduces caches, which are not aligned with the existing approach for caching scheduled events)
