### ISSUE TITLE
logrotate for debian package

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Core#582]
Logs of unifiedviews are huge after certain time. UV has to rotate the log files and take care of old logs.

**Comment by tomas-knap** [comment]
@Jan-Marcek  Please report the status

In config.properties, you may set up log rotation : e.g. frontend.log.keepDays = 3

So in the branch you propose we define yet another mechanism for rotating. 

What I agree is to reduce the logs on standard output and put them directly to log files, for which the rotation is driven by teh config.properties file

**Comment by tomas-knap** [comment]
See also: c8d5e823d41d64b516a11ecefadbe23b2b09be2d
c8d5e823d41d64b516a11ecefadbe23b2b09be2d

**Comment by hanecak** [comment]
OK, so c8d5e82 and c8d5e82 take care limiting the amount of logging.

Now, regarding log rotation: I agree with @tomas-knap  and my appology to @Jan-Marcek : In https://github.com/OpenDataNode/open-data-node/issues/257 I've asked for this but made a mistake: My focus was on catalina.out file, created due to use of separate Tomcat instances for (in this case) UnifiedViews Front-end. To maintain unified settings and maintenance (from Debian admin point of view), I've asked to add logrotate stuff. But ...

... But UnifiedViews back-end is not utilizing Tomcat instance, so it is not producing any unrotated catalina.out file and thus does not need logrotate settings.

So:
1. Jan, please drop logrotate parts for backend from the pull request
2. Jan, keep just frontend stuff, but make sure it rotatres just /var/log/unifiedviews/frontend/catalina.out (rest is already taken care of by slf4j)
3. Tomas, please re-evaluate and merge.

Thank you in advance.

**Comment by Jan-Marcek** [comment]
Your commit : c8d5e82  wasn't in the develop at that time. 
@hanecak it rotates only frontend's catalina.out
