### ISSUE TITLE
Cancelling a pipeline hangs from time to time

### ISSUE THREAD

**Issue by martinfmi** [UnifiedViews/Core#622]
When a pipeline is triggered and hangs (or is running for long) for some reason when you click on "Cancel" from the execution monitor canceling also hangs. Also there is no way to programatically (e.g. via the REST API) force cancelling of pipeline execution.

**Comment by tomas-knap** [comment]
Hi, the problem may be caused by the fact that in Java there is no way how to force thread to cancel - so it always works in a way that UV framework sets only a flag for the currently running DPU and such DPU should regularly check that and in case it is set it should cancel. For which DPU did it happen? (Btw. what you can do is that you restart backend, which at the start cleanse those executions being in the status "cancelling")

**Comment by martinfmi** [comment]
Thanks - as it happens rarely I haven't investigate which DPU could be the root cause. For now we can use the suggested workaround with the restart but it we would be nice if we can also trigger cancelling via the REST API.

**Comment by tomas-knap** [comment]
OK, created a related issue to have cancellation support via API
https://github.com/UnifiedViews/Core/issues/623
